// eslint.config.mjs — FR-018
// .mjs extension = always ESM, no "type":"module" needed in package.json.
//
// Key change from original: parserOptions.project → parserOptions.projectService
// projectService (v8 API) auto-discovers the nearest tsconfig.json for each file.
// This is correct for monorepos where each workspace package has its own tsconfig.
// The old `project: "./tsconfig.json"` only covered files in the root tsconfig —
// every file in apps/** and lib/** failed with "file not found in project".

import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import reactHooks from "eslint-plugin-react-hooks";
import prettierConfig from "eslint-config-prettier";
import { fileURLToPath } from "url";
import { dirname } from "path";

// ESM equivalent of __dirname (import.meta.dirname is Node 21.2+ only)
const __dirname = dirname(fileURLToPath(import.meta.url));

export default [
  // ── Global ignores ────────────────────────────────────────────────────────
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/.patch-backups/**",
      "pnpm-lock.yaml",
      "**/*.bak",
      "**/*.bak-*",
      // Auto-generated by orval — do not lint
      "lib/api-client-react/src/generated/**",
      "lib/api-zod/src/generated/**",
      // Plain JS tools — not TypeScript, skip type-aware linting
      "tools/**/*.js",
      "ecosystem.config.cjs",
    ],
  },

  // ── TypeScript source files (all workspace packages) ─────────────────────
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        // projectService: true — monorepo-safe.
        // For each file being linted, ESLint resolves the nearest tsconfig.json
        // in the file's ancestor directories. Each workspace package's own
        // tsconfig is used for type-aware rules on files within that package.
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
    },
    rules: {
      // Recommended rules (not type-checked — applied to all TS files safely)
      ...tsPlugin.configs["recommended"].rules,

      // Type-aware rules (require projectService — safe in monorepo with v8)
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": "warn",
    },
  },

  // ── React / frontend (react-hooks plugin) ────────────────────────────────
  {
    files: ["apps/r3-agi/src/**/*.ts", "apps/r3-agi/src/**/*.tsx"],
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },

  // ── Prettier compat — must be last ───────────────────────────────────────
  prettierConfig,
];
