// eslint.config.mjs — FR-018
// .mjs extension = always ESM, no "type":"module" needed in package.json.
//
// Architecture: two-block TypeScript strategy.
//
// Block 1 (all TS/TSX): non-type-aware recommended rules.
//   No projectService — r3-agi and lib/* use composite tsconfig references
//   which the project service does not follow, causing "file not found" errors.
//   All rules here work without type information.
//
// Block 2 (api-server only): type-aware rules via projectService.
//   api-server/tsconfig.json directly includes src/**, so the project service
//   resolves every file. Adds no-floating-promises which catches real bugs.
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import reactHooks from "eslint-plugin-react-hooks";
import prettierConfig from "eslint-config-prettier";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

export default [
  // ── Global ignores ────────────────────────────────────────────────────────
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/.patch-backups/**",
      "pnpm-lock.yaml",
      "**/*.bak",
      "**/*.bak-*",
      // Auto-generated by orval — do not lint
      "lib/api-client-react/src/generated/**",
      "lib/api-zod/src/generated/**",
      // Plain JS tools — not TypeScript, skip type-aware linting
      "tools/**/*.js",
      "tools/fix/**",
      "ecosystem.config.cjs",
    ],
  },
  // ── TypeScript: non-type-aware rules (all workspace packages) ─────────────
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: tsParser,
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
    },
    rules: {
      ...tsPlugin.configs["recommended"].rules,
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": "warn",
    },
  },
  // ── TypeScript: type-aware rules (api-server only) ────────────────────────
  {
    files: ["apps/api-server/**/*.ts"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
    },
  },
  // ── React / frontend (react-hooks plugin) ────────────────────────────────
  {
    files: ["apps/r3-agi/src/**/*.ts", "apps/r3-agi/src/**/*.tsx"],
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },
  // ── Prettier compat — must be last ───────────────────────────────────────
  prettierConfig,
];
